### ISSUE TITLE
[BUG] Could not find codec parameters for stream 2

### ISSUE THREAD

**Issue by sanj3k** [rubegartor/ReelSteady-Joiner#38]
Somehow since a while I have problems with stiching two videos together. In RSGO it starts to shake after the beginning of the second clip. Looking through the log the above mentioned debug message seems to be the interesting one. 

Shot on Gopro 10 in 4k50 high bitrate but with tweaked even higher bitrate through Gopro Labs QR code. Could this be the issue? I have uploaded both files and the to the following Google drive folder. Please have a look if you can get it to work again. :) 

https://drive.google.com/drive/folders/1eGMQCGTQiTH4JplqB1Hjokj8y8zaYIBi

**Comment by rubegartor** [comment]
After reviewing the logs and performing several tests with the videos, the problem does not come from ReelSteady Joiner, in general there is usually nothing mapped in stream 2, so it is ignored so it is not an error, I cannot confirm that It is due to the modified bitrate of the GoPro, perhaps it could also be due to some bug in the ReelSteady video processing. Have you been able to try another video?

**Comment by sanj3k** [comment]
It happens quite often within the last months. Usually I am quite lucky that it's not in the middle of a certain move which in this case is super unfortunate. 

What can I do with the rsgo devs about it? I can just provide them the stitched together video and ask whats the problem? Really unsure how to continue with it but thank you for confirming my problem!

**Comment by rubegartor** [comment]
It is definitely due to something wrong in ReelSteady Go 2, out of curiosity I tried to render the _joined.mp4 in ReelSteady Go 1 and everything was perfect. Small blurs in fast movements or with a lot of vibration, but normal. The only way to contact the developers is through Gopro support: https://gopro.com/help/ContactUs, good luck...
I enclose the .mp4 rendered with ReelSteady Go 1 for you to judge for yourself

https://drive.google.com/file/d/1SI6vNjuO7LpxEXqMsQ_bWlI2jIMexHSX

**Comment by sanj3k** [comment]
Thanks a lot !!!! At least now I have one stitched together smoothed and I will contact the support. Then I will close this issue. Once again thank your for your help!
