### ISSUE TITLE
Exporting joined .360 to .mp4 stops at chapter

### ISSUE THREAD

**Issue by thisisdylan** [rubegartor/ReelSteady-Joiner#48]
The joined 360 works fine, but when exporting to mp4, the file is stopped at the chapter.

**Comment by rubegartor** [comment]
I have not been able to reproduce the problem that you mention with the .360 files that I have. Would it be possible to get the original .360 files for further testing?

**Comment by thisisdylan** [comment]
Here is a folder with the 2 chapters (unjoined), the joined .360 file, the exported .mp4, and the export settings (you can see I made some keyframes).

https://mega.nz/folder/4gRFBRQC#_vPpgsKE1PQUMqfTpEJDug

**Comment by rubegartor** [comment]
Unfortunately I can't help you more with this case, I've been doing tests and ReelSteady Joiner is doing its job correctly, it correctly injects the gopro headers to be able to edit it later in GoPro Player. Perhaps the problem when exporting is due to a bug in GoPro Player, but I can't confirm it either, it may also be due to the fact that the metadata of the files required by GoPro is corrupted.

As a further clarification, ReelSteady Joiner is an application that uses the "udtacopy" script developed by GoPro Labs, so I have no control over GoPro Player or the "udtacopy" script, but as I mentioned before, it is working correctly and it does the job just fine on other .360 files I have.

The only thing that occurs to me is that you try other .360 files generated by your GoPro MAX to rule out that the problem is only with these files.

**Comment by thisisdylan** [comment]
I guess it is a limitation of GoPro Player. This occurs with other .360 files I've recorded as well.

I can export from 0:00 to 8:02, and 8:02 to the end. But I cannot export a video of any length if it crosses the chapter at 8:02.
